# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ntp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ntp.proto',
  package='hello',
  serialized_pb=_b('\n\tntp.proto\x12\x05hello\"a\n\rNTPDataPacket\x12\x14\n\x0creference_ts\x18\x01 \x01(\x03\x12\x11\n\torigin_ts\x18\x02 \x01(\x03\x12\x12\n\nreceive_ts\x18\x03 \x01(\x03\x12\x13\n\x0btransmit_ts\x18\x04 \x01(\x03\x42\x1a\n\x18\x63om.hello.suripu.api.ntp')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NTPDATAPACKET = _descriptor.Descriptor(
  name='NTPDataPacket',
  full_name='hello.NTPDataPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reference_ts', full_name='hello.NTPDataPacket.reference_ts', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin_ts', full_name='hello.NTPDataPacket.origin_ts', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receive_ts', full_name='hello.NTPDataPacket.receive_ts', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transmit_ts', full_name='hello.NTPDataPacket.transmit_ts', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['NTPDataPacket'] = _NTPDATAPACKET

NTPDataPacket = _reflection.GeneratedProtocolMessageType('NTPDataPacket', (_message.Message,), dict(
  DESCRIPTOR = _NTPDATAPACKET,
  __module__ = 'ntp_pb2'
  # @@protoc_insertion_point(class_scope:hello.NTPDataPacket)
  ))
_sym_db.RegisterMessage(NTPDataPacket)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.hello.suripu.api.ntp'))
# @@protoc_insertion_point(module_scope)
